export const contractAddress = '0x2525727733091f79c883d600654f165a9b2efca1';
export const contractABI = [
  {
    constant: true,
    inputs: [{ name: '', type: 'uint256' }],
    name: 'proposals',
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'text', type: 'string' },
      { name: 'voteCount', type: 'uint256' },
      { name: 'closed', type: 'bool' },
    ],
    payable: false,
    type: 'function',
  },
  {
    constant: false,
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'closeProposal',
    outputs: [],
    payable: false,
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: 'proposal', type: 'string' },
      { name: 'pro', type: 'bool' },
    ],
    name: 'vote',
    outputs: [],
    payable: false,
    type: 'function',
  },
  {
    constant: false,
    inputs: [{ name: 'proposal', type: 'string' }],
    name: 'addProposal',
    outputs: [],
    payable: false,
    type: 'function',
  },
  {
    constant: false,
    inputs: [],
    name: 'getProposalCount',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    type: 'function',
  },
  {
    constant: false,
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'getProposal',
    outputs: [
      { name: '', type: 'string' },
      { name: '', type: 'uint256' },
      { name: '', type: 'address' },
      { name: '', type: 'bool' },
    ],
    payable: false,
    type: 'function',
  },
  { payable: false, type: 'fallback' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'proposal', type: 'string' },
      { indexed: false, name: 'proposalCount', type: 'uint256' },
      { indexed: false, name: 'addr', type: 'address' },
    ],
    name: 'LogProposal',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'proposal', type: 'string' },
      { indexed: false, name: 'pro', type: 'bool' },
      { indexed: false, name: 'addr', type: 'address' },
    ],
    name: 'LogVote',
    type: 'event',
  },
];
